osx_image: xcode7.3
language: objective-c

script:
- xcodebuild clean build -project Sugar.xcodeproj -scheme Sugar-iOS -sdk iphonesimulator
- xcodebuild test -project Sugar.xcodeproj -scheme Sugar-iOS -sdk iphonesimulator
- xcodebuild clean build -project Sugar.xcodeproj -scheme Sugar-Mac -sdk macosx
- xcodebuild test -project Sugar.xcodeproj -scheme Sugar-Mac -sdk macosx
